CREATE TABLE PERFILES(
	ID_PERFIL INT NOT NULL PRIMARY KEY, 
	DESCRIPCION VARCHAR(50) NOT NULL,
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	USUARIO VARCHAR(50) NOT NULL, 
	PASSWORD VARCHAR(50) NOT NULL, 
	ID_PERFIL INT FOREIGN KEY REFERENCES PERFILES(ID_PERFIL) NOT NULL, 
	EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE ARTICULOS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_ARTICULO INT NOT NULL, 
	MARCA VARCHAR(50) NOT NULL, 
	MODELO VARCHAR(50) NOT NULL,
	CONSTRAINT UQ_ARTICULOS_ID UNIQUE(ID_ARTICULO)
);

CREATE TABLE REPUESTOS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_REPUESTO INT NOT NULL, 
	DESCRIPCION VARCHAR(50) NOT NULL,
	FABRICANTE VARCHAR(50), 
	PESO INT NOT NULL, 
	ALTO INT NOT NULL, 
	LARGO INT NOT NULL, 
	ANCHO INT NOT NULL,
	CONSTRAINT UQ_REPUESTOS_ID UNIQUE(ID_REPUESTO)
);

CREATE TABLE ESTADOS(
	ID_ESTADO INT NOT NULL PRIMARY KEY, 
	DESCRIPCION VARCHAR(50) NOT NULL
);

CREATE TABLE SINTOMAS(
	ID_SINTOMA INT NOT NULL PRIMARY KEY, 
	DESCRIPCION VARCHAR(50) NOT NULL,
	ID_REPUESTO INT FOREIGN KEY REFERENCES REPUESTOS(ID_REPUESTO) NOT NULL,
	CONSTRAINT UQ_SINTOMAS_ID UNIQUE(ID_SINTOMA)
);

CREATE TABLE STOCKS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_REPUESTO INT FOREIGN KEY REFERENCES REPUESTOS(ID_REPUESTO) NOT NULL,
	CANTIDAD INT NOT NULL,
);

CREATE TABLE REPARACIONES(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_ESTADO INT FOREIGN KEY REFERENCES ESTADOS(ID_ESTADO) NOT NULL,
	ID_ARTICULO INT FOREIGN KEY REFERENCES ARTICULOS(ID_ARTICULO) NOT NULL,
	FECHA_INSERCION DATE NOT NULL,
	FECHA_RECUPERACION DATE
);

CREATE TABLE REPARACIONES_ESTADO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_REPARACION INT FOREIGN KEY REFERENCES REPARACIONES(ID) NOT NULL,
	ID_ESTADO INT FOREIGN KEY REFERENCES ESTADOS(ID_ESTADO) NOT NULL,
	FECHA DATE NOT NULL
);

CREATE TABLE REPARACIONES_SINTOMAS(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_REPARACION INT FOREIGN KEY REFERENCES REPARACIONES(ID) NOT NULL,
	ID_SINTOMA INT FOREIGN KEY REFERENCES SINTOMAS(ID_SINTOMA) NOT NULL
);

CREATE TABLE ENVIOS(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	CALLE VARCHAR(50) NOT NULL, 
	NUMERO INT NOT NULL, 
	POBLACION VARCHAR(50) NOT NULL, 
	PROVINCIA VARCHAR(50) NOT NULL, 
	CODIGO_POSTAL VARCHAR(50) NOT NULL, 
	PERSONA_CONTACTO VARCHAR(50) NOT NULL, 
	TELEFONO INT NOT NULL,
	ID_REPARACION INT FOREIGN KEY REFERENCES REPARACIONES(ID) NOT NULL
);

CREATE TABLE RECOGIDAS(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
	CALLE VARCHAR(50) NOT NULL, 
	NUMERO INT NOT NULL, 
	POBLACION VARCHAR(50) NOT NULL, 
	PROVINCIA VARCHAR(50) NOT NULL, 
	CODIGO_POSTAL VARCHAR(50) NOT NULL, 
	PERSONA_CONTACTO VARCHAR(50) NOT NULL, 
	TELEFONO INT NOT NULL,
	ID_REPARACION INT FOREIGN KEY REFERENCES REPARACIONES(ID) NOT NULL
);

CREATE TABLE PUNTOS_RECOGIDA (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CIUDAD VARCHAR(50),
    DIRECCION VARCHAR(100),
    PROVINCIA VARCHAR(50),
    CODIGO_POSTAL VARCHAR(10),
    NOMBRE_CIUDAD VARCHAR(50),
    TELEFONO VARCHAR(20),
    HORARIO VARCHAR(50)
);





