SELECT R.ID_REPARACION, A.MARCA, A.MODELO, E.DESCRIPCION_ESTADO AS "ESTADO"
FROM REPARACIONES R
INNER JOIN ARTICULOS A ON R.ID_ARTICULO = A.ID_ARTICULO
LEFT JOIN (
    SELECT ID_REPARACION, ID_ESTADO, FECHA_ESTADO 
    FROM REPARACIONES_ESTADO R1 
    WHERE FECHA_ESTADO = (
        SELECT MAX(FECHA_ESTADO) 
        FROM REPARACIONES_ESTADO R2 
        WHERE R1.ID_REPARACION = R2.ID_REPARACION
    )
) RE ON R.ID_REPARACION = RE.ID_REPARACION
INNER JOIN ESTADOS E ON RE.ID_ESTADO = E.ID_ESTADO;


--OTRO TRY

SELECT R.ID_REPARACION, A.MARCA, A.MODELO, E.DESCRIPCION_ESTADO AS "ESTADO",
       RSR.ID_REPARACION_SINTOMA, S.DESCRIPCION_SINTOMA AS "SINTOMA", RP.DESCRIPCION_REPUESTO AS "REPUESTO"
FROM REPARACIONES R
INNER JOIN ARTICULOS A ON R.ID_ARTICULO = A.ID_ARTICULO
LEFT JOIN (
    SELECT ID_REPARACION, ID_ESTADO, FECHA_ESTADO 
    FROM REPARACIONES_ESTADO R1 
    WHERE FECHA_ESTADO = (
        SELECT MAX(FECHA_ESTADO) 
        FROM REPARACIONES_ESTADO R2 
        WHERE R1.ID_REPARACION = R2.ID_REPARACION
    )
) RE ON R.ID_REPARACION = RE.ID_REPARACION
INNER JOIN ESTADOS E ON RE.ID_ESTADO = E.ID_ESTADO
LEFT JOIN REPARACIONES_SINTOMAS_REPUESTO RSR ON R.ID_REPARACION = RSR.ID_REPARACION
LEFT JOIN SINTOMAS S ON RSR.ID_SINTOMA = S.ID_SINTOMA
LEFT JOIN REPUESTOS RP ON RSR.ID_REPUESTO = RP.ID_REPUESTO;