/*
	DESCRIPCION DE LA VISTA:		[EXPLICACIÓN BREVE]
	
	vista general de las reparaciones, con sus estados, sintomas,repuesto a usar ...

#######################################################################

	FECHA DE MODIFICACIÓN: 
	AUTOR:
	EXPLICACIÓN:		
	
#######################################################################
*/
ALTER VIEW V_REPARACION_SINTOMAS
AS	

	SELECT 
		R.ID_REPARACION, A.MARCA, A.MODELO, E.DESCRIPCION_ESTADO "ESTADO", DESCRIPCION_SINTOMA "SINTOMA", DESCRIPCION_REPUESTO "REPUESTO"
	FROM 
		REPARACIONES R
	LEFT JOIN 
		ARTICULOS A WITH (NOLOCK)
	ON 
		R.ID_ARTICULO = A.ID_ARTICULO
	LEFT JOIN
		ESTADOS E WITH (NOLOCK)
	ON 
		R.ID_ESTADO = E.ID_ESTADO
	LEFT JOIN
		REPARACIONES_ESTADO RE WITH (NOLOCK)
	ON 
		R.ID_ESTADO = RE.ID_REPARACION_ESTADO
	LEFT JOIN
		REPARACIONES_SINTOMAS_REPUESTO RSR WITH (NOLOCK)
	ON
		R.ID_REPARACION = RSR.ID_REPARACION
	LEFT JOIN
		SINTOMAS S WITH (NOLOCK)
	ON
		S.ID_SINTOMA = RSR.ID_SINTOMA
	LEFT JOIN
		REPUESTOS RP WITH (NOLOCK)
	ON 
		RSR.ID_REPUESTO = RP.ID_REPUESTO
		

		
	