/*
	DESCRIPCION DE LA VISTA:		[EXPLICACIÓN BREVE]
	
	vista general de las reparaciones, con sus estados, sintomas,repuesto a usar ...

#######################################################################

	FECHA DE MODIFICACIÓN: 
	AUTOR:
	EXPLICACIÓN:		
	
--#######################################################################
*/
ALTER VIEW V_REPARACION_SINTOMAS AS

SELECT
	RSR.ID_REPARACION_SINTOMA,
	RSR.ID_REPARACION,
	A.MARCA,
	A.MODELO,
	ES.DESCRIPCION_ESTADO ESTADO,
	S.DESCRIPCION_SINTOMA SINTOMA,
	R.DESCRIPCION_REPUESTO REPUESTO
FROM
	REPARACIONES_SINTOMAS_REPUESTO RSR WITH(NOLOCK)

	INNER JOIN SINTOMAS S WITH(NOLOCK)
	ON RSR.ID_SINTOMA = S.ID_SINTOMA

	INNER JOIN REPUESTOS R WITH(NOLOCK)
	ON RSR.ID_REPUESTO = R.ID_REPUESTO
	
	INNER JOIN REPARACIONES_SINTOMAS_ESTADO RSE WITH(NOLOCK)
	ON RSR.ID_REPARACION_SINTOMA = RSE.ID_REPARACION_SINTOMAS_ESTADO

	INNER JOIN ESTADOS_SINTOMA ES WITH(NOLOCK)
	ON RSE.ID_ESTADO_SINTOMA = ES.ID_ESTADO_SINTOMA

	INNER JOIN REPARACIONES REP WITH(NOLOCK)
	ON RSR.ID_REPARACION = REP.ID_REPARACION

	INNER JOIN ARTICULOS A WITH(NOLOCK)
	ON REP.ID_ARTICULO = A.ID_ARTICULO