/*
	DESCRIPCION DE LA VISTA:		[EXPLICACIÓN BREVE]
	
	vista general de las reparaciones, con sus estados, sintomas,repuesto a usar ...

#######################################################################

	FECHA DE MODIFICACIÓN: 
	AUTOR:
	EXPLICACIÓN:		
	
#######################################################################
*/
ALTER VIEW V_REPARACION_SINTOMAS
AS	

	SELECT DISTINCT R.ID_REPARACION, RSR.ID_REPARACION_SINTOMA, A.MARCA, A.MODELO, E.DESCRIPCION_ESTADO AS "ESTADO", S.DESCRIPCION_SINTOMA AS "SINTOMA", RP.DESCRIPCION_REPUESTO AS "REPUESTO"
FROM REPARACIONES R
	INNER JOIN ARTICULOS A 
		ON R.ID_ARTICULO = A.ID_ARTICULO
	LEFT JOIN REPARACIONES_ESTADO RE 
		ON R.ID_REPARACION = RE.ID_REPARACION
	LEFT JOIN ESTADOS E ON RE.ID_ESTADO = E.ID_ESTADO
	INNER JOIN REPARACIONES_SINTOMAS_REPUESTO RSR 
		ON R.ID_REPARACION = RSR.ID_REPARACION
	INNER JOIN SINTOMAS S 
		ON RSR.ID_SINTOMA = S.ID_SINTOMA
	INNER JOIN REPUESTOS RP 
		ON RSR.ID_REPUESTO = RP.ID_REPUESTO


		

		
	