DECLARE @ID_ARTICULO    INT
DECLARE @SINTOMAS_JSON  VARCHAR(MAX)
DECLARE @REPUESTOS_JSON VARCHAR(MAX)
DECLARE @INVOKER        INT
DECLARE @RETCODE        INT
DECLARE @MENSAJE        VARCHAR(8000)

SET @ID_ARTICULO = 5
SET @SINTOMAS_JSON = '[10,20]'
SET @REPUESTOS_JSON = '[1,2]'
SET @INVOKER = 0
SET @RETCODE = 0
SET @MENSAJE = ''

EXEC PA_ALTA_REPARACION 
	@ID_ARTICULO ,
	@SINTOMAS_JSON ,
	@REPUESTOS_JSON ,
	@INVOKER ,
	@RETCODE OUTPUT,
	@MENSAJE OUTPUT

PRINT 'RETCODE: ' + CAST(@RETCODE AS VARCHAR(MAX))
PRINT 'MENSAJE: ' + CAST(@MENSAJE AS VARCHAR(MAX))

