// Generated by https://quicktype.io

export interface GeoCode {
    place_id:     number;
    licence:      string;
    osm_type:     string;
    osm_id:       number;
    lat:          string;
    lon:          string;
    display_name: string;
    address:      Address;
    boundingbox:  string[];
}

export interface Address {
    house_number:     string;
    road:             string;
    village:          string;
    municipality:     string;
    state:            string;
    "ISO3166-2-lvl4": string;
    postcode:         string;
    country:          string;
    country_code:     string;
}
