// Generated by https://quicktype.io

export interface PuntosRecogida {
    id_Punto_Recogida: number;
    ciudad:            string;
    direccion:         string;
    provincia:         string;
    codigo_Postal:     string;
    nombre_Ciudad:     string;
    telefono:          string;
    horario:           string;
}
