USE FCT_9
GO

/*
#######################################################################

	NOMBRE DEL FUNCIÓN:			PA_ALTA_REPARACION
	FECHA DE CREACIÓN: 			[FECHA]
	AUTOR:					[AUTOR]
	RUTA REPOSITORIO:			[RUTA]
	USADO POR:				WEB o APP
	DESCRIPCION DE LA VISTA:		[EXPLICACIÓN BREVE]
	

#######################################################################

	FECHA DE MODIFICACIÓN: 
	AUTOR:
	EXPLICACIÓN:		
	
#######################################################################
*/



ALTER PROCEDURE PA_ALTA_REPARACION

	@ID_ARTICULO		INT,
	@SINTOMAS_JSON		VARCHAR(MAX),
	@REPUESTOS_JSON		VARCHAR(MAX),
	@RECOGIDA_JSON		VARCHAR(MAX),
	@ENVIO_JSON		VARCHAR(MAX),

	@INVOKER		INT,
	
	@RETCODE		INT		OUTPUT,
	@MENSAJE		VARCHAR(8000)	OUTPUT
AS
	
	DECLARE @NTRANS			INT = @@TRANCOUNT	

	SET @MENSAJE = ''
	SET @RETCODE = 0	


	BEGIN TRY
	
		--COMPROBACIONES
		IF ISNULL(@ID_ARTICULO,'') = ''
		BEGIN
			SET @RETCODE = 10
			SET @MENSAJE = 'El ID recibido esta vacío'
			RETURN
		END
			
		IF NOT EXISTS(SELECT ID_ARTICULO FROM ARTICULOS WHERE ID_ARTICULO = @ID_ARTICULO)
		BEGIN
			set @MENSAJE = 'NO existe el ID del articulo'
			SET @RETCODE = 20
			RETURN
		END

		-- --------------------------------------------------------------------
		-- TRANSACCIÓN
		-- --------------------------------------------------------------------
		IF @NTRANS = 0 BEGIN TRANSACTION [TR_ALTA_REPARACION]		
			
			--SI TODO OK SE INSERTA REGISTROS

			--TABLA TEMPORAL DE SINTOMAS, REPUESTOS, RECOGIDA, ENVIO

			CREATE TABLE #TEMPTABLE_SINTOMAS(ID_SINTOMA INT)

			CREATE TABLE #TEMPTABLE_REPUESTOS(ID_REPUESTO INT)

			CREATE TABLE #TEMPTABLE_RECOGIDA(
				CALLE VARCHAR(50), 
				NUMERO INT, 
				POBLACION VARCHAR(50), 
				PROVINCIA VARCHAR(50), 
				CODIGO_POSTAL VARCHAR(50), 
				PERSONA_CONTACTO VARCHAR(50), 
				TELEFONO INT, 
				ID_REPARACION INT
			)

			CREATE TABLE #TEMPTABLE_ENVIO(
				CALLE VARCHAR(50), 
				NUMERO INT, 
				POBLACION VARCHAR(50), 
				PROVINCIA VARCHAR(50), 
				CODIGO_POSTAL VARCHAR(50), 
				PERSONA_CONTACTO VARCHAR(50), 
				TELEFONO INT, 
				ID_REPARACION INT
			)

			--INSERTAMOS DATOS EN TABLAS TEMPORALES

			INSERT INTO #TEMPTABLE_SINTOMAS(ID_SINTOMA)
			SELECT VALUE
			FROM OPENJSON(@SINTOMAS_JSON)
			
			INSERT INTO #TEMPTABLE_REPUESTOS(ID_REPUESTO)
			SELECT VALUE
			FROM OPENJSON(@REPUESTOS_JSON)

			INSERT INTO #TEMPTABLE_RECOGIDA(
				CALLE,
				NUMERO,
				POBLACION,
				PROVINCIA,
				CODIGO_POSTAL,
				PERSONA_CONTACTO,
				TELEFONO
			)
			SELECT 
				Calle_Recogida,
				Numero_Recogida,
				Poblacion_Recogida,
				Provincia_Recogida,
				Codigo_Postal_Recogida,
				Persona_Contacto_Recogida,
				Telefono_Recogida

			FROM OPENJSON(@RECOGIDA_JSON)
			WITH(
				Calle_Recogida VARCHAR(50),
				Numero_Recogida INT, 
				Poblacion_Recogida VARCHAR(50), 
				Provincia_Recogida VARCHAR(50),
				Codigo_Postal_Recogida VARCHAR(50), 
				Persona_Contacto_Recogida VARCHAR(50), 
				Telefono_Recogida INT
			)
			
			
			INSERT INTO #TEMPTABLE_ENVIO(
				CALLE,
				NUMERO,
				POBLACION,
				PROVINCIA,
				CODIGO_POSTAL,
				PERSONA_CONTACTO,
				TELEFONO
			)
			SELECT 
				Calle_Envio,
				Numero_Envio, 
				Poblacion_Envio, 
				Provincia_Envio,
				Codigo_Postal_Envio, 
				Persona_Contacto_Envio, 
				Telefono_Envio

			FROM OPENJSON(@ENVIO_JSON)
			WITH(
				Calle_Envio VARCHAR(50),
				Numero_Envio INT, 
				Poblacion_Envio VARCHAR(50), 
				Provincia_Envio VARCHAR(50),
				Codigo_Postal_Envio VARCHAR(50), 
				Persona_Contacto_Envio VARCHAR(50), 
				Telefono_Envio INT
			)

			/*
			SELECT * FROM #TEMPTABLE_SINTOMAS
			SELECT * FROM #TEMPTABLE_REPUESTOS


			SELECT 
			(SELECT TOP 1 ID_REPARACION FROM REPARACIONES ORDER BY ID_REPARACION DESC),
				T1.ID_SINTOMA,
				T2.ID_REPUESTO
			FROM
				 #TEMPTABLE_SINTOMAS AS T1
				 
				LEFT JOIN SINTOMAS AS T2
				ON T1.ID_SINTOMA = T2.ID_SINTOMA
				

			*/


			
			--INSERTAMOS REPARACION

			INSERT INTO REPARACIONES(
				ID_ESTADO_REPARACION,
				ID_ARTICULO,
				FECHA_INSERCION
			) VALUES(
				101,
				@ID_ARTICULO,
				GETDATE()
			);


			-- SE INSERTAR CAMPOS EN REPARACIONES_SINTOMAS_ESTADO
			
			INSERT INTO REPARACIONES_SINTOMAS_ESTADO
			(
				ID_REPARACION,
				ID_ESTADO_REPARACION,
				ID_SINTOMA,
				ID_ESTADO_SINTOMA,
				FECHA_ESTADO
			) SELECT 
				(SELECT TOP 1 ID_REPARACION FROM REPARACIONES ORDER BY ID_REPARACION DESC),
				101, 
				T.ID_SINTOMA,
				11,
				GETDATE()
			FROM
				 #TEMPTABLE_SINTOMAS AS T


			-- SE INSERTAR CAMPOS EN REPARACIONES_SINTOMAS_REPUESTO

			INSERT INTO REPARACIONES_SINTOMAS_REPUESTO
			(
				ID_REPARACION,
				ID_SINTOMA,
				ID_REPUESTO
			) 
			SELECT 
				(SELECT TOP 1 ID_REPARACION FROM REPARACIONES ORDER BY ID_REPARACION DESC),
					T1.ID_SINTOMA,
					T2.ID_REPUESTO
				FROM
					#TEMPTABLE_SINTOMAS AS T1
				 
					LEFT JOIN SINTOMAS AS T2
					ON T1.ID_SINTOMA = T2.ID_SINTOMA
				


			--SE INSERTAN DATOS DE LA RECOGIDA

			INSERT INTO RECOGIDAS (
				CALLE, 
				NUMERO, 
				POBLACION, 
				PROVINCIA, 
				CODIGO_POSTAL, 
				PERSONA_CONTACTO, 
				TELEFONO, 
				ID_REPARACION
			)SELECT 
				T.CALLE,
				T.NUMERO,
				T.POBLACION,
				T.PROVINCIA,
				T.CODIGO_POSTAL,
				T.PERSONA_CONTACTO,
				T.TELEFONO,
				(SELECT TOP 1 ID_REPARACION FROM REPARACIONES ORDER BY ID_REPARACION DESC)
			FROM
				#TEMPTABLE_RECOGIDA AS T

			-- SE INSERTAN DATOS DEL ENVIO
			
			INSERT INTO ENVIOS (
				CALLE, 
				NUMERO, 
				POBLACION, 
				PROVINCIA, 
				CODIGO_POSTAL, 
				PERSONA_CONTACTO, 
				TELEFONO, 
				ID_REPARACION
			)SELECT 
				T.CALLE,
				T.NUMERO,
				T.POBLACION,
				T.PROVINCIA,
				T.CODIGO_POSTAL,
				T.PERSONA_CONTACTO,
				T.TELEFONO,
				(SELECT TOP 1 ID_REPARACION FROM REPARACIONES ORDER BY ID_REPARACION DESC)
			FROM
				#TEMPTABLE_ENVIO AS T


			--UPDATE EN STOCKS

			UPDATE STOCKS SET CANTIDAD = (CANTIDAD - 1) WHERE ID_REPUESTO IN (SELECT ID_REPUESTO FROM #TEMPTABLE_REPUESTOS) 
			


		IF @NTRANS = 0 AND @@TRANCOUNT > 0 COMMIT TRANSACTION [TR_ALTA_REPARACION]

		SET @RETCODE = 0
		SET @MENSAJE = ''

	END TRY
	BEGIN CATCH
		
		SET @MENSAJE = ERROR_MESSAGE()
		IF @NTRANS = 0 AND @@TRANCOUNT > 0 ROLLBACK TRANSACTION [TR_ALTA_REPARACION]

	END CATCH

	RETURN @RETCODE