USE FCT_9
GO

/*
#######################################################################

	NOMBRE DEL FUNCIÓN:			PA_BAJA_ARTICULO
	FECHA DE CREACIÓN: 			[FECHA]
	AUTOR:					[AUTOR]
	RUTA REPOSITORIO:			[RUTA]
	USADO POR:				WEB o APP
	DESCRIPCION DE LA VISTA:		[EXPLICACIÓN BREVE]
	

#######################################################################

	FECHA DE MODIFICACIÓN: 
	AUTOR:
	EXPLICACIÓN:		
	
#######################################################################
*/



ALTER PROCEDURE PA_BAJA_ARTICULO

	@ID_ARTICULO		INTEGER,

	@INVOKER		INTEGER,
	
	@RETCODE		INT		OUTPUT,
	@MENSAJE		VARCHAR(8000)	OUTPUT
AS
	
	DECLARE @NTRANS			INT = @@TRANCOUNT	

	SET @MENSAJE = ''
	SET @RETCODE = 0	


	BEGIN TRY
	
		--COMPROBACIONES
		IF ISNULL(@ID_ARTICULO,'') = ''
		BEGIN
			SET @RETCODE = 10
			SET @MENSAJE = 'El ID recibido esta vacío'
			RETURN
		END
		
		IF NOT EXISTS(SELECT @ID_ARTICULO FROM ARTICULOS WHERE ID_ARTICULO = @ID_ARTICULO)
		BEGIN
			SET @MENSAJE = 'NO existe un ARTICULO con ese ID'
			SET @RETCODE = 20
			RETURN
		END

		-- --------------------------------------------------------------------
		-- TRANSACCIÓN
		-- --------------------------------------------------------------------
		IF @NTRANS = 0 BEGIN TRANSACTION [TR_BAJA_ARTICULO]		
			
			
			--SI TODO OK CAMBIAMOS EL REGISTRO
			IF(SELECT ACTIVO FROM ARTICULOS WHERE ID_ARTICULO = @ID_ARTICULO) = 1
			BEGIN
				UPDATE ARTICULOS SET ACTIVO = 0 WHERE ID_ARTICULO = @ID_ARTICULO
			END
			ELSE
			BEGIN
				UPDATE ARTICULOS SET ACTIVO = 1 WHERE ID_ARTICULO = @ID_ARTICULO
			END


		IF @NTRANS = 0 AND @@TRANCOUNT > 0 COMMIT TRANSACTION [TR_BAJA_ARTICULO]

		SET @RETCODE = 0
		SET @MENSAJE = ''

	END TRY
	BEGIN CATCH
		
		SET @MENSAJE = ERROR_MESSAGE()
		IF @NTRANS = 0 AND @@TRANCOUNT > 0 ROLLBACK TRANSACTION [TR_BAJA_ARTICULO]

	END CATCH

	RETURN @RETCODE