USE FCT_9
GO

/*
#######################################################################

	NOMBRE DEL FUNCIÓN:			PA_BAJA_REPUESTO
	FECHA DE CREACIÓN: 			[FECHA]
	AUTOR:					[AUTOR]
	RUTA REPOSITORIO:			[RUTA]
	USADO POR:				WEB o APP
	DESCRIPCION DE LA VISTA:		[EXPLICACIÓN BREVE]
	

#######################################################################

	FECHA DE MODIFICACIÓN: 
	AUTOR:
	EXPLICACIÓN:		
	
#######################################################################
*/



CREATE PROCEDURE PA_BAJA_REPUESTO

	@ID_REPUESTO		INTEGER,

	@INVOKER		INTEGER,
	
	@RETCODE		INT		OUTPUT,
	@MENSAJE		VARCHAR(8000)	OUTPUT
AS
	
	DECLARE @NTRANS			INT = @@TRANCOUNT	

	SET @MENSAJE = ''
	SET @RETCODE = 0	


	BEGIN TRY
	
		--COMPROBACIONES
		IF ISNULL(@ID_REPUESTO,'') = ''
		BEGIN
			SET @RETCODE = 10
			SET @MENSAJE = 'El ID recibido esta vacío'
			RETURN
		END
		
		IF NOT EXISTS(SELECT ID_REPUESTO FROM REPUESTOS WHERE ID_REPUESTO = @ID_REPUESTO)
		BEGIN
			SET @MENSAJE = 'NO existe un REPUESTO con ese ID'
			SET @RETCODE = 20
			RETURN
		END

		--COMPROBAMOS STOCK
		IF (SELECT CANTIDAD FROM STOCKS WHERE ID_REPUESTO = @ID_REPUESTO) > 0
		BEGIN
			SET @MENSAJE = 'NO se puede dar de baja un REPUESTO si aun tiene stock'
			SET @RETCODE = 30
			RETURN
		END
		-- --------------------------------------------------------------------
		-- TRANSACCIÓN
		-- --------------------------------------------------------------------
		IF @NTRANS = 0 BEGIN TRANSACTION [TR_ALTA_REPARACION]		
			
			
			--SI TODO OK CAMBIAMOS EL REGISTRO
			IF(SELECT ACTIVO FROM REPUESTOS WHERE ID_REPUESTO = @ID_REPUESTO) = 1
			BEGIN
				UPDATE REPUESTOS SET ACTIVO = 0 WHERE ID_REPUESTO = @ID_REPUESTO
			END
			ELSE
			BEGIN
				UPDATE REPUESTOS SET ACTIVO = 1 WHERE ID_REPUESTO = @ID_REPUESTO
			END

		IF @NTRANS = 0 AND @@TRANCOUNT > 0 COMMIT TRANSACTION [TR_ALTA_REPARACION]

		SET @RETCODE = 0
		SET @MENSAJE = ''

	END TRY
	BEGIN CATCH
		
		SET @MENSAJE = ERROR_MESSAGE()
		IF @NTRANS = 0 AND @@TRANCOUNT > 0 ROLLBACK TRANSACTION [TR_ALTA_REPARACION]

	END CATCH

	RETURN @RETCODE