USE FCT_9
GO

/*
#######################################################################

	NOMBRE DEL FUNCIÓN:			PA_LOGIN
	FECHA DE CREACIÓN: 			[FECHA]
	AUTOR:					[AUTOR]
	RUTA REPOSITORIO:			[RUTA]
	USADO POR:				WEB o APP
	DESCRIPCION DE LA VISTA:		[EXPLICACIÓN BREVE]
	

#######################################################################

	FECHA DE MODIFICACIÓN: 
	AUTOR:
	EXPLICACIÓN:		
	
#######################################################################
*/

/*
	SI TODO OK -> RETCODE = 0
	SI TODO ERROR -> RETCODE < 0
	SI TODO ERROR CONTROLADO -> RETCODE > 0
*/

--ALTER PROCEDURE PA_LOGIN	
ALTER PROCEDURE PA_LOGIN	

	
	@LOGIN			VARCHAR(50),
	@PASSWORD		VARCHAR(500),

	@INVOKER		INTEGER,
	
	@JSON_OUT		VARCHAR(8000)	OUTPUT,
	@RETCODE		INT		OUTPUT,
	@MENSAJE		VARCHAR(8000)	OUTPUT
AS
	
	DECLARE @NTRANS			INT = @@TRANCOUNT	

	SET @MENSAJE = ''
	SET @RETCODE = 0	


	BEGIN TRY	

		IF ISNULL(@LOGIN,'') = ''
		BEGIN
			SET @RETCODE = 10
			SET @MENSAJE = 'El login recibido esta vacío.'
			RETURN
		END

		IF NOT EXISTS(SELECT ID_USUARIO FROM USUARIOS WHERE USUARIO = @LOGIN AND PASSWORD = @PASSWORD)
		BEGIN
			SET @RETCODE = 20
			SET @MENSAJE = 'Datos incorrectos.'
			RETURN
		END

		IF NOT EXISTS(SELECT ID_USUARIO FROM USUARIOS WHERE USUARIO = @LOGIN AND PASSWORD = @PASSWORD AND ACTIVO = 1)
		BEGIN
			SET @RETCODE = 30
			SET @MENSAJE = 'Usuario desactivado.'
			RETURN
		END

			SET @JSON_OUT = (
			SELECT	
				ID_USUARIO,
				USUARIO,
				--PASSWORD,
				ID_PERFIL,
				EMAIL,
				ACTIVO
				--SALT
			FROM	USUARIOS
			WHERE	USUARIO = @LOGIN
			FOR JSON AUTO,  WITHOUT_ARRAY_WRAPPER)
		

		-- --------------------------------------------------------------------
		-- TRANSACCIÓN
		-- --------------------------------------------------------------------
		IF @NTRANS = 0 BEGIN TRANSACTION [TR_LOGIN]		
			
			-- CUERPO DEL PA
			-- INSTRUCCIONES INSERT, UPDATE, DELETE, LLAMADAS A OTROS PAS, ETC



		IF @NTRANS = 0 AND @@TRANCOUNT > 0 COMMIT TRANSACTION [TR_LOGIN]
		
		SET @RETCODE = 0
		SET @MENSAJE = ''

	END TRY
	BEGIN CATCH
		
		SET @MENSAJE = ERROR_MESSAGE()
		SET @RETCODE = -1
		IF @NTRANS = 0 AND @@TRANCOUNT > 0 ROLLBACK TRANSACTION [TR_LOGIN]

	END CATCH

